FROM --platform=${BUILDPLATFORM} golang:1.16-buster AS builder

ARG GOPROXY
WORKDIR /go/src
COPY .. ./

ENV GOBIN=/go/bin
ARG TARGETARCH
RUN GOARCH=${TARGETARCH} make build

FROM ghcr.io/querycap/distroless/static-debian10:latest

ARG TARGETARCH
COPY --from=builder /go/bin/goproxy-linux-${TARGETARCH} /go/bin/goproxy

ENTRYPOINT ["/go/bin/goproxy"]